# Generated by Django 5.2.4 on 2025-07-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('profile_pic', models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='', verbose_name='Фото профиля')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Готов', 'Готов')], max_length=200, null=True, verbose_name='Статус заказа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Клиент')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product', verbose_name='Изделие')),
            ],
        ),
    ]
