# Generated by Django 5.2.4 on 2025-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Готов', 'Готов')], default='В ожидании', max_length=200, null=True, verbose_name='Статус заказа'),
        ),
    ]
